### PR TITLE
Prevent duplicate tree items when loading more (emulator)

### PR DESCRIPTION
**Pull request by wwlorey**
When calling `listBlobsByHierarchy` with the local emulator, all the nested children of the first blob directory will be loaded before any other resources at that same level. This is different from the non-emulated case which lists all blobs and directories at one level without loading nested children.

Because the emulator is loading all nested children but their parent isn't expanded, only the parent is returned after clicking "Load More..." (assuming greater than `maxPageSize` children in the directory):

Screen Shot 2020-10-26 at 2 41 06 PM

This fix prevents duplicate tree items from showing up when loading more children from emulated blob containers. ~This means that clicking "Load More..." sometimes won't do anything as it loads the nested children.~

~Fixes~ Related: https://github.com/microsoft/vscode-azurestorage/issues/659

### CODE REVIEW

**Comment by nturinski** [comment]
I'm not sure that having Load More do nothing is really acceptable behavior.  It makes it look like something is broken/unresponsive.  Maybe we can use load it again if we see that the array is empty after you do the filter?

**Comment by wwlorey** [comment]
> I'm not sure that having Load More do nothing is really acceptable behavior. It makes it look like something is broken/unresponsive. Maybe we can use load it again if we see that the array is empty after you do the filter?

That's a good point - I added logic to keep loading until a new tree item loads

**Comment by nturinski** [comment]
So this is adding a Load More button even when there aren't any children to load.  I have two storage accounts here with the exact same contents:

image


Furthermore, this skips the first folder and is loading one folder at a time now:
image

I think it might be better to investigate how to use the continuation token properly than this workaround.  It seems like the potential to cause a lot of bugs is pretty high.

**Comment by nturinski** [comment]
Okay, I think I see the problem here.

When you call https://github.com/microsoft/vscode-azurestorage/blob/main/src/utils/blobUtils.ts#L40, this response is an iterator.  There's another property on `next` besides `value`, which is called `done`.

When you `listBlobsByHierarchy` an Azure blob, `done` is set to 'true' however, if you check on the emulator, it's marked as 'false'.
image

What this means is that there's actually more to the response and you have to keep invoking `next()` to get the remainder of the response. I tried it once and you'll notice that the prefixes are different:

image

So you'll need to iterate through the response until `done === true`.  I guess Azure was already taking care of this for us, but the emulator doesn't.

**Comment by wwlorey** [comment]
Per standup discussion: it looks like this loading behavior is a problem with Azurite. I just pushed a temporary fix that should prevent the weird "load more" behavior unless people have large blob directories

**Review by nturinski — APPROVED** [review]

**Pull request merged**
