### PR TITLE
BlobContainerFS core logic

### PR DESCRIPTION
**Pull request by JasonYeMSFT**
Implements FileSystemProvider for Azure blobs. The new FS provider no longer queries the tree view for the container node and provides a faster readFile/readDirectory experience. It also implements rename for hierarchical namespace containers.

### CODE REVIEW

**Comment by alexweininger** [comment]
Got the build to pass! 🎉

**Comment by alexweininger** [comment]
We'll need to also support attached storage accounts.

I just tested the current fs provider and it works perfectly with attached storage accounts. So we have two options:
1. Remove old fs provider and support attached accounts in the new provider
2. Keep old fs provider around solely for attached account support

I'm sorta voting for option 2 since the attached accounts feature may need a larger rework to get it to work well with the new fs provider.

**Comment by JasonYeMSFT** [comment]
I reverted breaking changes to the AzureStorageFS and added code to use it for attached storage accounts.

**Review by alexweininger — APPROVED** [review]
In my testing it works really well. Lets merge this to get CTI testing done on it and then we can see about releasing this to unblock users from this scenario.

We can leave the fancier stuff like integrating this with the tree view for later.

**Comment by JasonYeMSFT** [comment]
Is there anything needed before merging the PR?

**Review by alexweininger — APPROVED** [review]

**Comment by alexweininger** [comment]
> Is there anything needed before merging the PR?

Go ahead and merge.

**Pull request merged**
